import React, { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router';
import { useStrategyStore } from '../../../stores/useStrategyStore';
import { usePlannerStore, type SlotLifecycleStatus } from '../../../stores/usePlannerStore';
import {
  Sparkles,
  Copy,
  Check,
  Lightbulb,
  Target,
  Brain,
  Loader2,
  Calendar,
  Download,
  CheckCircle2,
  X,
} from 'lucide-react';
import { PageHeader } from '../../../components/ui/PageHeader';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { Input } from '../../../components/ui/Input';
import { Alert } from '../../../components/ui/Alert';
import { sanitizeStrategyTopic, type StrategyBrief } from '../../../lib/strategyTopic';

const getDefaultScheduledAt = (): string => {
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(10, 0, 0, 0);
  const year = tomorrow.getFullYear();
  const month = String(tomorrow.getMonth() + 1).padStart(2, '0');
  const day = String(tomorrow.getDate()).padStart(2, '0');
  const hours = String(tomorrow.getHours()).padStart(2, '0');
  const minutes = String(tomorrow.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day}T${hours}:${minutes}`;
};

const buildNotesFromBrief = (brief: StrategyBrief): string => {
  const sections: string[] = [];
  if (brief.script_outline?.hook) {
    sections.push(`Hook:\n${brief.script_outline.hook}`);
  }
  if (brief.script_outline?.retention_mid) {
    sections.push(`Key Points & Retention:\n${brief.script_outline.retention_mid}`);
  }
  if (brief.script_outline?.cta) {
    sections.push(`CTA:\n${brief.script_outline.cta}`);
  }
  if (brief.tags && brief.tags.length > 0) {
    const formattedTags = brief.tags.map((t) => (t.startsWith('#') ? t : `#${t}`)).join(' ');
    sections.push(`SEO Tags:\n${formattedTags}`);
  }
  if (brief.strategy_insight) {
    sections.push(`Strategy Insight:\n${brief.strategy_insight}`);
  }
  return sections.join('\n\n');
};

const buildScriptOutlineMarkdown = (brief: StrategyBrief): string => {
  return `# Script Outline: ${brief.topic}

## Hook
${brief.script_outline?.hook || 'N/A'}

## Key Points & Retention
${brief.script_outline?.retention_mid || 'N/A'}

## Call to Action (CTA)
${brief.script_outline?.cta || 'N/A'}

---
Generated by CreatorIQ Strategy Suite
`;
};

const triggerDownload = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const sanitizeFilename = (name: string, suffix: string, ext: string): string => {
  const clean = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
  return `${clean || 'strategy'}-${suffix}.${ext}`;
};

export const StrategyPage: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [topic, setTopic] = useState('');
  const [goal, setGoal] = useState('Max engagement');
  const [copiedTitleIndex, setCopiedTitleIndex] = useState<number | null>(null);
  const [copiedOutline, setCopiedOutline] = useState(false);
  const [copiedTags, setCopiedTags] = useState(false);

  // Schedule Modal State
  const [isScheduleModalOpen, setIsScheduleModalOpen] = useState(false);
  const [scheduleTopic, setScheduleTopic] = useState('');
  const [scheduleDate, setScheduleDate] = useState(getDefaultScheduledAt());
  const [scheduleStatus, setScheduleStatus] = useState<SlotLifecycleStatus>('not_started');
  const [scheduleNotes, setScheduleNotes] = useState('');
  const [isScheduling, setIsScheduling] = useState(false);
  const [scheduleSuccess, setScheduleSuccess] = useState(false);

  const { brief, sessionId, isLoading, error, generateBrief } = useStrategyStore();
  const handledNavState = useRef(false);

  useEffect(() => {
    const state = location.state as { topic?: string; autoGenerate?: boolean } | null;
    if (!state?.topic || handledNavState.current) return;

    handledNavState.current = true;
    const nextTopic = state.topic.trim();
    setTopic(nextTopic);
    if (state.autoGenerate && nextTopic) {
      void generateBrief(nextTopic, goal);
    }
    navigate(location.pathname, { replace: true, state: null });
  }, [location.state, location.pathname, navigate, generateBrief, goal]);

  const handleCopyTitle = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedTitleIndex(index);
    setTimeout(() => setCopiedTitleIndex(null), 2000);
  };

  const handleCopyOutline = () => {
    if (!brief) return;
    navigator.clipboard.writeText(buildScriptOutlineMarkdown(brief));
    setCopiedOutline(true);
    setTimeout(() => setCopiedOutline(false), 2000);
  };

  const handleExportOutline = () => {
    if (!brief) return;
    const markdown = buildScriptOutlineMarkdown(brief);
    const filename = sanitizeFilename(brief.topic, 'outline', 'md');
    triggerDownload(markdown, filename, 'text/markdown;charset=utf-8');
  };

  const handleCopyTags = () => {
    if (!brief) return;
    const tagsText = (brief.tags ?? []).join(', ');
    navigator.clipboard.writeText(tagsText);
    setCopiedTags(true);
    setTimeout(() => setCopiedTags(false), 2000);
  };

  const handleExportTags = () => {
    if (!brief) return;
    const tagsText = (brief.tags ?? []).join(', ');
    const filename = sanitizeFilename(brief.topic, 'tags', 'txt');
    triggerDownload(tagsText, filename, 'text/plain;charset=utf-8');
  };

  const handleOpenScheduleModal = () => {
    if (!brief) return;
    setScheduleTopic(brief.titles?.[0]?.text || brief.topic);
    setScheduleDate(getDefaultScheduledAt());
    setScheduleStatus('not_started');
    setScheduleNotes(buildNotesFromBrief(brief));
    setIsScheduleModalOpen(true);
  };

  const handleScheduleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!scheduleTopic.trim()) return;

    setIsScheduling(true);
    try {
      const isoDate = new Date(scheduleDate).toISOString();
      await usePlannerStore.getState().createSlot({
        topic: scheduleTopic.trim(),
        scheduled_at: isoDate,
        status: scheduleStatus,
        strategy_session_id: sessionId || undefined,
        notes: scheduleNotes.trim(),
      });
      setIsScheduleModalOpen(false);
      setScheduleSuccess(true);
    } catch (err) {
      console.error('Failed to create planner slot:', err);
    } finally {
      setIsScheduling(false);
    }
  };

  return (
    <div className="space-y-6 pb-6 animate-in text-[#ededed]">
      <PageHeader
        title="Content Strategy Suite"
        description="Generate a data-backed creator intelligence brief grounded in your channel context and live search demand."
      />

      {error && <Alert variant="error">{error}</Alert>}

      {scheduleSuccess && (
        <div className="flex items-center justify-between gap-3 rounded-lg border border-[#166534] bg-[#0e2316] p-4 text-xs text-emerald-300 animate-in">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0" />
            <div>
              <p className="font-semibold text-emerald-200">Slot scheduled in Content Planner!</p>
              <p className="text-[11px] text-emerald-400 mt-0.5">
                Your video slot has been added to the calendar linked to this strategy session.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              onClick={() => navigate('/app/planner')}
              className="text-xs h-7"
            >
              <Calendar className="mr-1.5 h-3 w-3" />
              Open Planner
            </Button>
            <button
              type="button"
              onClick={() => setScheduleSuccess(false)}
              className="p-1 text-emerald-400 hover:text-emerald-200 rounded cursor-pointer"
              title="Dismiss"
            >
              <X className="h-3.5 w-3.5" />
            </button>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-12">
        <div className="space-y-4 lg:col-span-4">
          <Card variant="elevated" className="space-y-4 border-[#242424] bg-[#121212] p-5">
            <div>
              <label className="text-xs font-medium text-neutral-400">Target Concept Topic</label>
              <div className="mt-1.5">
                <Input
                  icon={<Lightbulb className="h-4 w-4 text-neutral-500" />}
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="e.g. AI Coding Agents in 2026"
                />
              </div>
            </div>
            <div>
              <label className="text-xs font-medium text-neutral-400">Primary Goal</label>
              <div className="relative mt-1.5">
                <Target className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-500" />
                <select
                  value={goal}
                  onChange={(e) => setGoal(e.target.value)}
                  className="h-9 w-full appearance-none rounded-lg border border-[#282828] bg-[#141414] pl-9 pr-3 text-xs text-[#ededed] focus:border-[#4f46e5] focus:outline-none cursor-pointer"
                >
                  <option value="Max engagement">Max engagement</option>
                  <option value="Audience growth">Audience growth</option>
                  <option value="Monetization focus">Monetization focus</option>
                </select>
              </div>
            </div>
            <Button
              className="w-full"
              onClick={() => {
                const cleaned = sanitizeStrategyTopic(topic);
                if (cleaned) void generateBrief(cleaned, goal);
              }}
              disabled={isLoading || !sanitizeStrategyTopic(topic)}
            >
              {isLoading ? 'Generating brief...' : 'Generate Strategy Brief'}
            </Button>
          </Card>

          <Card variant="default" className="border-[#222222] bg-[#121212] p-4">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-indigo-400" />
              <h3 className="text-xs font-semibold text-neutral-300">Creator Intelligence</h3>
            </div>
            <p className="mt-2 text-xs leading-relaxed text-neutral-400">
              Generated briefs synthesize your live audience geography, creator tier and keyword velocities via OpenRouter AI.
            </p>
          </Card>
        </div>

        <div className="lg:col-span-8">
          {!brief ? (
            <Card variant="elevated" className="flex min-h-[320px] flex-col items-center justify-center border-dashed border-[#282828] bg-[#101010] text-center p-8">
              <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-[#181818] border border-[#2a2a2a] text-neutral-400">
                <Brain className="h-5 w-5" />
              </div>
              <h3 className="text-sm font-semibold text-neutral-200">
                {isLoading ? 'Generating your creator strategy brief...' : 'No active brief generated'}
              </h3>
              <p className="mt-1.5 max-w-xs text-xs text-neutral-500 leading-relaxed">
                {isLoading
                  ? 'Analyzing keyword velocity, audience retention patterns, and viral angles...'
                  : 'Enter a concept topic on the left or select a trend to generate an actionable brief.'}
              </p>
              {isLoading && <Loader2 className="mt-4 h-5 w-5 animate-spin text-indigo-400" />}
            </Card>
          ) : (
            <Card variant="elevated" className="space-y-6 border-[#242424] bg-[#121212] p-6">
              <section className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-[#1c1c1c] pb-4">
                <div>
                  <div className="flex items-center gap-2">
                    <p className="text-[11px] font-bold uppercase tracking-wider text-indigo-400">Strategy Report</p>
                    {sessionId && (
                      <span className="rounded bg-[#1a1a1a] px-2 py-0.5 text-[10px] font-mono text-neutral-400 border border-[#2a2a2a]">
                        ID: {sessionId.slice(0, 8)}
                      </span>
                    )}
                  </div>
                  <h2 className="mt-1 text-lg font-bold text-white">{brief.topic}</h2>
                </div>
                <Button
                  variant="primary"
                  onClick={handleOpenScheduleModal}
                  className="shrink-0 text-xs h-8 px-3"
                >
                  <Calendar className="mr-1.5 h-3.5 w-3.5" />
                  Schedule to Planner
                </Button>
              </section>

              {/* Strategic Insight */}
              <section>
                <div className="rounded-lg border border-[#2c2854] bg-[#15132d] p-4 text-xs leading-relaxed text-indigo-200">
                  <span className="font-semibold text-white block mb-1 flex items-center gap-1.5">
                    <Sparkles className="h-3.5 w-3.5 text-indigo-400" /> Strategic Callout
                  </span>
                  {brief.strategy_insight}
                </div>
              </section>

              {/* Optimized Title Ideas */}
              <section>
                <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-400 mb-2.5">
                  Optimized Video Titles
                </h3>
                <div className="space-y-2">
                  {(brief.titles ?? []).map((t, i) => (
                    <div
                      key={i}
                      className="flex items-center justify-between gap-3 rounded-lg border border-[#242424] bg-[#161616] px-3.5 py-2.5 transition-colors hover:border-[#383838]"
                    >
                      <div>
                        <p className="text-xs font-semibold text-neutral-200">{t.text}</p>
                        <p className="text-[10px] text-neutral-500 mt-0.5">{t.hook_type || 'Algorithmic hook'}</p>
                      </div>
                      <button
                        type="button"
                        onClick={() => handleCopyTitle(t.text, i)}
                        className="rounded p-1 text-neutral-500 hover:bg-[#222222] hover:text-white transition-colors cursor-pointer"
                        title="Copy title"
                      >
                        {copiedTitleIndex === i ? (
                          <Check className="h-3.5 w-3.5 text-emerald-400" />
                        ) : (
                          <Copy className="h-3.5 w-3.5" />
                        )}
                      </button>
                    </div>
                  ))}
                </div>
              </section>

              {/* Script Outline */}
              <section>
                <div className="flex items-center justify-between mb-2.5">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-400">
                    Structured Script Outline
                  </h3>
                  <div className="flex items-center gap-2">
                    <Button
                      type="button"
                      variant="secondary"
                      size="sm"
                      onClick={handleCopyOutline}
                      className="h-7 px-2 text-[11px]"
                    >
                      {copiedOutline ? (
                        <>
                          <Check className="mr-1 h-3 w-3 text-emerald-400" />
                          Copied
                        </>
                      ) : (
                        <>
                          <Copy className="mr-1 h-3 w-3" />
                          Copy
                        </>
                      )}
                    </Button>
                    <Button
                      type="button"
                      variant="secondary"
                      size="sm"
                      onClick={handleExportOutline}
                      className="h-7 px-2 text-[11px]"
                    >
                      <Download className="mr-1 h-3 w-3" />
                      Markdown
                    </Button>
                  </div>
                </div>
                <div className="space-y-2.5 text-xs">
                  <div className="rounded-lg border border-[#2a284c] bg-[#141226] p-3.5">
                    <p className="text-[10px] font-bold uppercase tracking-wider text-indigo-300">Hook (0:00 - 0:15)</p>
                    <p className="mt-1.5 text-neutral-200 leading-relaxed">{brief.script_outline?.hook}</p>
                  </div>
                  <div className="rounded-lg border border-[#242424] bg-[#161616] p-3.5">
                    <p className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Retention & Value (Core)</p>
                    <p className="mt-1.5 text-neutral-300 leading-relaxed">{brief.script_outline?.retention_mid}</p>
                  </div>
                  <div className="rounded-lg border border-[#262626] bg-[#181818] p-3.5">
                    <p className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Call to Action (CTA)</p>
                    <p className="mt-1.5 text-neutral-300 leading-relaxed">{brief.script_outline?.cta}</p>
                  </div>
                </div>
              </section>

              {/* SEO Tags */}
              <section>
                <div className="flex items-center justify-between mb-2.5">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-400">
                    SEO Query Tags
                  </h3>
                  <div className="flex items-center gap-2">
                    <Button
                      type="button"
                      variant="secondary"
                      size="sm"
                      onClick={handleCopyTags}
                      className="h-7 px-2 text-[11px]"
                    >
                      {copiedTags ? (
                        <>
                          <Check className="mr-1 h-3 w-3 text-emerald-400" />
                          Copied
                        </>
                      ) : (
                        <>
                          <Copy className="mr-1 h-3 w-3" />
                          Copy Tags
                        </>
                      )}
                    </Button>
                    <Button
                      type="button"
                      variant="secondary"
                      size="sm"
                      onClick={handleExportTags}
                      className="h-7 px-2 text-[11px]"
                    >
                      <Download className="mr-1 h-3 w-3" />
                      Export TXT
                    </Button>
                  </div>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {(brief.tags ?? []).map((tag, i) => (
                    <span
                      key={i}
                      className="rounded bg-[#161616] border border-[#242424] px-2 py-0.5 text-[11px] text-neutral-300"
                    >
                      #{tag}
                    </span>
                  ))}
                </div>
              </section>
            </Card>
          )}
        </div>
      </div>

      {/* Schedule to Planner Modal (Dark Mode) */}
      {isScheduleModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-xs animate-in">
          <div
            className="w-full max-w-lg rounded-xl bg-[#141414] p-6 shadow-2xl border border-[#2a2a2a]"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between pb-3 border-b border-[#222222]">
              <div className="flex items-center gap-2.5">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#1e1e1e] text-neutral-300 border border-[#2c2c2c]">
                  <Calendar className="h-4 w-4" />
                </div>
                <div>
                  <h3 className="text-sm font-bold text-white">Schedule to Planner</h3>
                  <p className="text-[11px] text-neutral-500">Add this brief to your production calendar</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setIsScheduleModalOpen(false)}
                className="p-1 text-neutral-500 hover:text-white rounded cursor-pointer"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <form onSubmit={handleScheduleSubmit} className="mt-4 space-y-3.5">
              <div>
                <label className="block text-xs font-medium text-neutral-300 mb-1">
                  Video Title / Topic *
                </label>
                <Input
                  value={scheduleTopic}
                  onChange={(e) => setScheduleTopic(e.target.value)}
                  placeholder="e.g. 5 AI Coding Agents You Need"
                  required
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-neutral-300 mb-1">
                    Target Date & Time *
                  </label>
                  <input
                    type="datetime-local"
                    value={scheduleDate}
                    onChange={(e) => setScheduleDate(e.target.value)}
                    required
                    className="h-9 w-full rounded-lg border border-[#282828] bg-[#161616] px-2.5 text-xs text-[#ededed] focus:border-[#4f46e5] focus:outline-none"
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-neutral-300 mb-1">
                    Initial Status
                  </label>
                  <select
                    value={scheduleStatus}
                    onChange={(e) => setScheduleStatus(e.target.value as SlotLifecycleStatus)}
                    className="h-9 w-full rounded-lg border border-[#282828] bg-[#161616] px-2.5 text-xs text-[#ededed] focus:border-[#4f46e5] focus:outline-none cursor-pointer"
                  >
                    <option value="not_started">Not Started</option>
                    <option value="scripting">Scripting</option>
                    <option value="recording">Recording</option>
                    <option value="editing">Editing</option>
                    <option value="ready">Ready to Publish</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-neutral-300 mb-1">
                  Notes / Outline Summary
                </label>
                <textarea
                  rows={4}
                  value={scheduleNotes}
                  onChange={(e) => setScheduleNotes(e.target.value)}
                  className="w-full rounded-lg border border-[#282828] bg-[#161616] p-2.5 text-xs text-[#ededed] placeholder-neutral-500 focus:border-[#4f46e5] focus:outline-none"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-3 border-t border-[#222222]">
                <Button
                  type="button"
                  variant="secondary"
                  size="sm"
                  onClick={() => setIsScheduleModalOpen(false)}
                >
                  Cancel
                </Button>
                <Button type="submit" size="sm" disabled={isScheduling || !scheduleTopic.trim()}>
                  {isScheduling ? 'Scheduling...' : 'Schedule Slot'}
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
